import { StyleSheet } from 'react-native';
import * as commonStyle from './commonStyle';

export const BOOK_BTN_HEIGHT = commonStyle.screenHeight / 10.5;
export const BOOK_BTN_WIDTH = commonStyle.screenWidth / 1.12;
export const font = commonStyle.screenHeight / 36;

const PAPER = '#F5EFE6';
const PAPER_DARK = '#E8DECF';
const INK = '#342C24';
const SUBTLE = '#7D7268';
const CARD = '#FCFAF6';
const ACTION_BG = '#5E4633';
const ACTION_BG_SOFT = '#6E5844';
const SHADOW = 'rgba(73, 53, 34, 0.12)';

export const homeStyles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: PAPER,
    alignItems: 'center',
    overflow: 'hidden',
  },
  backgroundGlowTop: {
    position: 'absolute',
    top: -commonStyle.screenWidth * 0.22,
    right: -commonStyle.screenWidth * 0.1,
    width: commonStyle.screenWidth * 0.72,
    height: commonStyle.screenWidth * 0.72,
    borderRadius: commonStyle.screenWidth,
    backgroundColor: '#E9DCCD',
  },
  backgroundGlowBottom: {
    position: 'absolute',
    bottom: -commonStyle.screenWidth * 0.18,
    left: -commonStyle.screenWidth * 0.12,
    width: commonStyle.screenWidth * 0.62,
    height: commonStyle.screenWidth * 0.62,
    borderRadius: commonStyle.screenWidth,
    backgroundColor: '#ECE3D8',
  },
  topSpacer: {
    width: '100%',
    paddingTop: commonStyle.screenHeight * 0.075,
    paddingHorizontal: 24,
    paddingBottom: 10,
  },
  eyebrow: {
    fontSize: 12,
    letterSpacing: 2.2,
    textTransform: 'uppercase',
    color: SUBTLE,
    marginBottom: 6,
  },
  screenCaption: {
    fontSize: 24,
    fontWeight: '700',
    color: INK,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  wordbookQuickBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: ACTION_BG,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  wordbookQuickBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  verticalScrollContainer: {
    width: commonStyle.screenWidth * 0.92,
    paddingTop: 8,
    paddingBottom: commonStyle.screenWidth / 6 + commonStyle.screenHeight * 0.045,
  },
  listHeaderStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  listHeaderTextWrap: {
    flex: 1,
  },
  listHeaderAccentBar: {
    width: 3,
    height: 36,
    borderRadius: 999,
    backgroundColor: '#8A6A52',
    marginRight: 12,
  },
  listHeaderTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: INK,
    marginBottom: 2,
  },
  listHeaderDescription: {
    fontSize: 12,
    lineHeight: 16,
    color: '#6F6359',
  },
  emptyCard: {
    backgroundColor: CARD,
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 22,
    borderWidth: 1,
    borderColor: PAPER_DARK,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: INK,
    marginBottom: 8,
  },
  emptyDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: SUBTLE,
    textAlign: 'center',
  },
  bookCardWrap: {
    marginBottom: 14,
  },
  bookBtn: {
    minHeight: BOOK_BTN_HEIGHT,
    backgroundColor: CARD,
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PAPER_DARK,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 18,
    elevation: 5,
    overflow: 'hidden',
  },
  bookSpine: {
    width: 10,
    alignSelf: 'stretch',
    borderTopLeftRadius: 24,
    borderBottomLeftRadius: 24,
  },
  bookMainArea: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 10,
    paddingVertical: 16,
  },
  bookIconBadge: {
    width: commonStyle.screenWidth / 8.5,
    height: commonStyle.screenWidth / 8.5,
    borderRadius: commonStyle.screenWidth,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  bookIconGlyphWrap: {
    width: commonStyle.screenWidth / 16,
    height: commonStyle.screenWidth / 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookIconGlyph: {
    textAlign: 'center',
    includeFontPadding: false,
    marginTop: 0.5,
  },
  bookTextBlock: {
    flex: 1,
    justifyContent: 'center',
  },
  bookTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: INK,
    marginBottom: 4,
  },
  bookSubtitle: {
    fontSize: 12,
    color: SUBTLE,
  },
  bookMenuButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1E8DC',
  },
  bookMenuContent: {
    backgroundColor: '#FFFDF9',
    marginTop: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8DDD0',
    paddingVertical: 6,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 6,
  },
  bottomMenuContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  addBookBtn: {
    position: 'absolute',
    right: 20,
    bottom: commonStyle.screenHeight * 0.02,
    backgroundColor: ACTION_BG,
    borderWidth: 1,
    borderColor: '#7D644E',
    borderRadius: commonStyle.screenHeight,
    width: commonStyle.screenWidth / 6,
    height: commonStyle.screenWidth / 6,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2E241B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },
  manualBtn: {
    position: 'absolute',
    left: 20,
    bottom: commonStyle.screenHeight * 0.02 + (commonStyle.screenWidth / 6 - commonStyle.screenWidth / 7) / 2,
    backgroundColor: ACTION_BG_SOFT,
    borderWidth: 1,
    borderColor: '#816955',
    borderRadius: 16,
    width: commonStyle.screenWidth / 7,
    height: commonStyle.screenWidth / 7,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2E241B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 5,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(39, 30, 22, 0.16)',
  },
  modalBackdropCenter: {
    flex: 1,
    backgroundColor: 'rgba(39, 30, 22, 0.22)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  newBookOptionsOverlay: {
    marginHorizontal: commonStyle.screenWidth * 0.04,
    marginBottom: commonStyle.screenHeight * 0.11,
    backgroundColor: '#FFFDF9',
    borderRadius: 24,
    paddingTop: 18,
    paddingBottom: 20,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: PAPER_DARK,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 18,
    elevation: 6,
  },
  paletteTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: INK,
    marginBottom: 14,
    paddingHorizontal: 8,
  },
  paletteGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  newBookBtn: {
    marginHorizontal: 8,
    marginBottom: 8,
  },
  paletteSwatch: {
    width: commonStyle.screenWidth / 7.5,
    height: commonStyle.screenWidth / 7.5,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EEE3D7',
  },
  paletteIconGlyphWrap: {
    width: commonStyle.screenWidth / 7.5,
    height: commonStyle.screenWidth / 7.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newBookBtnIcon: {
    textAlign: 'center',
    includeFontPadding: false,
  },
  renameModalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#FFFDF9',
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: PAPER_DARK,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 1,
    shadowRadius: 22,
    elevation: 8,
  },
  renameModalTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: INK,
    marginBottom: 14,
  },
  renameInput: {
    borderWidth: 1,
    borderColor: PAPER_DARK,
    borderRadius: 14,
    backgroundColor: '#FFFCF7',
    height: 48,
    paddingHorizontal: 14,
    paddingVertical: 0,
    fontSize: 16,
    lineHeight: 20,
    textAlignVertical: 'center',
    includeFontPadding: false,
    color: INK,
  },
  renameActionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 18,
    gap: 10,
  },
  renameGhostButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#F1E8DC',
  },
  renameGhostButtonText: {
    color: '#6C5A49',
    fontWeight: '700',
  },
  renamePrimaryButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: ACTION_BG,
  },
  renamePrimaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
});